version: "3.8"
services:
  web:
    build:
      context: ./web
    command: bash -c "npm install --unsafe-perm && npm run dev"
    volumes:
      - './web:/web'
    ports:
      - 3004:3000
      - 5556:5555
    stdin_open: true
    env_file:
      - ./.env
    depends_on:
      - db
  # nginx:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./nginx/dev.d:/etc/nginx/conf.d
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - web
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5435:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data