server {
    listen 80;
    server_name localhost;

    # Socket.IO: Realtime-Service
    location /socket.io/ {
        proxy_pass http://realtime:3001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 75s;
    }

    # Next.js Hot Module Reloading im Development-Modus
    location /_next/webpack-hmr {
        proxy_pass http://web:3000/_next/webpack-hmr;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
    }

    # Next.js-App und API-Routen
    location / {
        proxy_pass http://web:3000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}